# Generated by Django 4.2.5 on 2023-09-27 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_person_date_added_alter_person_tel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_added',
            field=models.DateField(default=datetime.date(2023, 9, 27)),
        ),
    ]
