# Generated by Django 4.2.5 on 2023-10-11 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_alter_person_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('tel_number', models.CharField(max_length=20)),
                ('date_added', models.DateField(default=datetime.date(2023, 10, 11))),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
