# Generated by Django 4.2.5 on 2023-10-12 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_contact_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='profession1',
            field=models.CharField(default='abcd', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='profession2',
            field=models.CharField(default='abcd', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateField(default=datetime.date(2023, 10, 12)),
        ),
    ]
