# Generated by Django 4.2.5 on 2023-10-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_contact_profession1_contact_profession2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='error_message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
