# Generated by Django 4.2.5 on 2023-10-13 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_contact_error_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='error_message',
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateField(default=datetime.date(2023, 10, 13)),
        ),
    ]
