# Generated by Django 4.2.5 on 2023-10-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_remove_contact_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='error_message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
